ServerUptime:
  ServerUptime: '&7[&bServer Uptime&7]'
  Days: '&bDay'
  Hours: '&bHours'
  Minutes: '&bMinutes'
  Seconds: '&bSeconds'
  Permissions: true
  NoPermissions: '&cYou are not authorized to do this!'
#Minecraft Color Codes: https://minecraft.wiki/w/Formatting_codes#Color_codes
  numbers:
    Days: '&7'
    Hours: '&7'
    Minutes: '&7'
    Seconds: '&7'
